name: Neuron_tests
on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and run tests
      run: |
        gcc -o test.exe -m64 -std=c++11 NeuronTest.cpp -static-libgcc
        ./test.exe
